# Generated by Django 4.2.7 on 2024-02-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezadoArchivo', models.CharField(max_length=162, unique=True)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HeaderLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezadoLote', models.CharField(max_length=162, unique=True)),
                ('encabezadoArchivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.headerfile')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registroDetalle', models.CharField(max_length=162)),
                ('encabezadoLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.headerlote')),
            ],
        ),
    ]
